# Generated by Django 4.1.3 on 2023-01-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_category_post_tags_reply_post_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': 'replies'},
        ),
    ]
